version: '3.8'
services:
  mysql:
    image: mysql:8
    ports:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: local_mysql
      MYSQL_USER: local_mysql_own
      MYSQL_PASSWORD: "12345678"
    cap_add:
      - SYS_NICE  # https://stackoverflow.com/a/55706057/1855840
  redis:
    image: redis:7.2.3-alpine3.18
    ports:
      - "6379"
    environment:
      REDIS_PASSWORD: 12345678
